/*****************************************************************************

		Copyright (c) My Company

 Project:  prologProject
 FileName: PROLOGPROJECT.INC
 Purpose:  Project's global declarations
 Written by: Visual Prolog
 Comments:
*****************************************************************************/


/*****************************************************************************
			User's Declarations
*****************************************************************************/
global domains
  DB_SELECTOR = browselist_db	% For treebrowser tool
  FILE = fileselector1; fileselector2 % To be edited

include "lab7.pre"

include "lab8.pre"

include "lab9.pre"

include "lab10.pre"

include "lab11.pre"
